### ISSUE TITLE
./injector problem

### ISSUE THREAD

**Issue by bigpeter911** [8dcc/tf2-cheat#15]
whenever i type sudo ./injector.sh into the terminal i get an error saying no command "./injector"
what should i do?

**Comment by bigpeter911** [comment]
> whenever i type sudo ./injector.sh into the terminal i get an error saying no command "./injector" what should i do?

fixed by typin ./inject

**Comment by throw198333** [comment]
I still have this issue and im unsure how to fix it i tried typing in ./inject as well and that didnt fix it either

**Comment by throw198333** [comment]
yeah I did the issue was that I had to open a command prompt window in the tf2cheats folder and then run the command 

sudo ./inject.sh.

 you need to update the info on your readme cause its extremely wrong. there is no file called ./injector.sh. 

please also add this to your readme about installing dependencies https://github.com/8dcc/tf2-cheat/issues/12#issuecomment-1869779907 this fixed my issue with installing the dependencies 

in terms of the font I couldn't install it at all, the instructions all lead to dead ends on your part so I had to do my own research and found out to install them you have to run all the font commands as root and the instructions you gave didnt work at all. so i had to google the actual font name and follow the install on the official github instructions of the creator of the font
